import json, re
from pathlib import Path
R=Path(__file__).resolve().parents[1]
# id, title, short introduction, rules, examples, trap
chapters=[
('present','Simple present & present progressive','Gewohnheiten und Dinge, die gerade passieren.', ['Simple present: I/you/we/they play; he/she/it plays.','Verneinung: don’t/doesn’t + Grundform. Fragen: Do/Does + Person + Grundform?','Present progressive: am/is/are + Verb-ing. Verneinung: am not/isn’t/aren’t.','Usually, often, every day → Gewohnheit. Look!, listen!, now → gerade im Gang.','Schreibweise: make → making, run → running, study → studies. Zustandsverben wie know stehen meist nicht im progressive.'],[['Ella feeds the cat every morning.','Regelmäßig: feeds.'],['Ella is feeding the cat now.','Gerade jetzt: is feeding.']],'Nach does/doesn’t steht kein zusätzliches -s am Verb.'),
('past','Simple past & past progressive','Von abgeschlossenen Erlebnissen erzählen.', ['Simple past: regelmäßige Verben mit -ed; unregelmäßige Formen lernen.','go–went, buy–bought, see–saw, write–wrote, think–thought, give–gave, hurt–hurt.','Verneinung: didn’t + Grundform. Frage: Did + Person + Grundform?','Past progressive: was/were + Verb-ing für eine Handlung im Verlauf.','When the doorbell rang, I was reading: kurzes Ereignis unterbricht längere Handlung.','Schreibweise: carry → carried, try → tried, stop → stopped.'],[['We visited York last summer.','Abgeschlossene Vergangenheit.'],['I was sleeping when you called.','Hintergrundhandlung und Unterbrechung.']],'Did trägt schon die Vergangenheit: didn’t go, nicht didn’t went.'),
('perfect','Present perfect oder simple past?','Vergangene Handlungen und ihr Ergebnis jetzt.', ['Present perfect: have/has + past participle (dritte Verbform).','go–went–gone; see–saw–seen; write–wrote–written; do–did–done; hear–heard–heard.','Für diese Wiederholung: Eine Handlung ist geschehen und ihr Ergebnis ist jetzt wichtig.','Already, just und yet helfen oft, das Ergebnis einzuordnen. Entscheidend ist der Zusammenhang.','Ein abgeschlossener Zeitpunkt wie yesterday, last week oder in 2020 verlangt in der Regel simple past.','Frage: Have you finished? Verneinung: She hasn’t finished yet.'],[['I have lost my ticket.','Es fehlt jetzt noch.'],['I lost my ticket yesterday.','Der Zeitpunkt gestern steht im Vordergrund.']],'Nach have/has braucht man die dritte Verbform: has gone, nicht has went.'),
('future','Zukunft & if-Sätze Typ 1','Pläne, Vorhersagen und mögliche Bedingungen.', ['Will + Grundform: Vorhersagen, spontane Entscheidungen, Versprechen.','Am/is/are going to + Grundform: Pläne oder sichtbare Anzeichen.','If + simple present, Hauptsatz mit will + Grundform.','Feste Fahrpläne: simple present für die Zukunft, z. B. The train leaves at nine tomorrow.','Bei Typ 1 kann der Hauptsatz auch can oder einen Imperativ enthalten: If you need help, ask me.','Allgemeine Bedingung: If I am tired, I go to bed. Beide Teilsätze stehen im simple present.','Will not = won’t. Going to wird über be verneint: isn’t going to.'],[['If it is sunny, we will cycle to the lake.','Mögliche Bedingung und ihre Folge.'],['We are going to visit Grandma.','Ein geplanter Besuch.']],'Nicht If it will rain, sondern If it rains.'),
('questions','Fragen & question tags','Hilfsverben richtig einsetzen.', ['Simple present: Do/Does + Person + Grundform?','Simple past: Did + Person + Grundform? Nach did keine Vergangenheitsform.','Be und Modalverben bilden Fragen ohne do: Are you ready? Can she swim?','Question tags: positiver Satz → negativer Anhang und umgekehrt.','Das Hilfsverb wiederholen: You have finished, haven’t you?','Have als Vollverb mit do: They have a dog, don’t they?','Frage nach dem Subjekt: Who called? Kein did nötig.','Fragen mit Präposition: Who are you waiting for? Die Präposition gehört zu wait for.'],[['Where did you stay?','Did + Grundform.'],['She isn’t here, is she?','Negativer Satz, positiver Anhang.']],'Question tags müssen zu Person und Zeitform des Hauptsatzes passen.'),
('modals','Modalverben & Ersatzformen','Können, müssen, dürfen und nicht müssen.', ['Nach can, could, must und mustn’t folgt die Grundform ohne to.','Can: Fähigkeit; could: Fähigkeit in der Vergangenheit.','May: Erlaubnis; might: Möglichkeit; should: Rat. Auch danach steht die Grundform ohne to.','Must / have to: Pflicht. Mustn’t: Verbot. Needn’t / don’t have to: nicht nötig.','Vergangenheit von must: had to. Erlaubnis: was/were allowed to.','Fähigkeit in anderen Zeiten: be able to, z. B. will be able to.','Bei he/she/it: has to. Frage: Does she have to …?'],[['We had to wait yesterday.','Pflicht in der Vergangenheit.'],['You don’t have to come, but you mustn’t be late if you do.','Nicht nötig und verboten sind unterschiedliche Aussagen.']],'Mustn’t bedeutet nicht dürfen, nicht nicht müssen.'),
('comparison','Adjektive vergleichen','Steigerung und Vergleiche mit as und than.', ['Kurz: small–smaller–smallest. Verdoppeln: hot–hotter–hottest.','Konsonant + y: easy–easier–easiest.','Lang: interesting–more interesting–most interesting.','Unregelmäßig: good–better–best; bad–worse–worst.','Ungleich: bigger than. Gleich: as big as.','Der Superlativ steht oft mit the: the tallest girl.'],[['This path is shorter than that path.','Vergleich mit than.'],['My bike is as old as your bike.','Gleicher Grad mit as … as.']],'Nicht more easy oder as tall like.'),
('quantifiers','Mengenwörter','Much, many, some, any und a lot of.', ['Many, a few: zählbare Dinge im Plural (many books).','Much, a little: nicht zählbare Mengen (much water).','A lot of / lots of: beides möglich. Enough = genug.','Some meist in positiven Aussagen, any in neutralen Fragen und Verneinungen.','Bei Bitten und Angeboten oft some: Can I have some tea?','Most students = die meisten Schüler allgemein; most of the students = die meisten einer bestimmten Gruppe.'],[['There isn’t much time, but there are many questions.','Time ist nicht zählbar, questions schon.'],['Would you like some juice?','Angebot mit some.']],'People ist zählbar: many people, nicht much people.'),
('pronouns','Pronomen & Besitz','Their, there, they’re und der Apostroph.', ['Subjekte: I, you, he, she, it, we, they. Objekte: me, you, him, her, it, us, them.','Possessivbegleiter stehen vor einem Nomen: my, your, his, her, its, our, their.','There are = es gibt; their = ihr; they’re = they are.','Besitz: Mia’s bike. Regelmäßiger Plural: the girls’ room. Unregelmäßiger Plural: children’s toys.','Its zeigt Besitz; it’s heißt it is oder it has.','This/that: ein Ding; these/those: mehrere Dinge. This/these für Nähe, that/those für Entfernung.','Somebody/someone: jemand; anybody/anyone oft in Fragen; nobody/no one: niemand. Something/anything/nothing beziehen sich auf Dinge.'],[['Their friends are here. They’re in the kitchen.','Besitzwort und Kurzform unterscheiden.'],['This is my parents’ car.','Plural auf -s: nur Apostroph.']],'Ein einfacher Plural hat keinen Apostroph: two phones.'),
('relatives','Relativsätze','Personen und Dinge genauer beschreiben.', ['Who für Menschen; which für Dinge und Tiere. That kann beides ersetzen.','Whose zeigt Besitz: a girl whose brother …','Where steht für einen Ort: the village where I live.','Objektpronomen darf entfallen: the film (that) we watched.','Subjektpronomen darf nicht entfallen: the film that won the prize.','Who’s ist who is/has, nicht whose.'],[['I know a boy who speaks Welsh.','Who beschreibt eine Person.'],['This is the woman whose bag we found.','Whose zeigt die Zugehörigkeit.']],'Nach the book passt which/that, nicht what.'),
('prepositions','Präpositionen & Zeitangaben','Kleine Wörter mit großer Wirkung.', ['At + Uhrzeit; on + Tag/Datum; in + Monat/Jahr.','In the morning/afternoon/evening, aber at night.','Feste Verbindungen: interested in, listen to, wait for, one of.','Between = zwischen, next to = neben, opposite = gegenüber.','Half past seven = 7:30; a quarter to eight = 7:45.','O’clock nur bei vollen Stunden: six o’clock. Bei 6.15 pm kein o’clock.'],[['We meet on Friday at four o’clock.','Tag mit on, Uhrzeit mit at.'],['He is interested in space.','Feste Verbindung mit in.']],'Präpositionen nicht Wort für Wort aus dem Deutschen übersetzen.'),
('connectors','Sätze verbinden','Because, although, while und during.', ['Because = weil (Grund). So = also/deshalb (Folge). So that = damit (Zweck).','Although = obwohl; but = aber.','While + ganzer Satz; during + Nomen.','Before = bevor/vor; after = nachdem/nach.','If = falls (Bedingung); when = wenn/als (Zeitpunkt).','Then = dann; than = als bei Vergleichen.'],[['While I was reading, it rained.','Nach while folgt ein Satz.'],['It rained during our picnic.','Nach during folgt ein Nomen.']],'During the lesson, aber while we were learning.'),
('plural','Mehrzahl & unregelmäßige Nomen','Children, feet und people sicher verwenden.', ['Meist -s: book–books. Nach s/sh/ch/x oft -es: box–boxes.','Konsonant + y → -ies: baby–babies. Vokal + y: boy–boys.','Child–children, foot–feet, tooth–teeth, mouse–mice, woman–women, man–men.','Life–lives, wife–wives. Die Ausnahmen einzeln lernen.','Person → people; people braucht ein Verb im Plural: people are.'],[['The children are playing.','Children ist schon Plural.'],['My feet hurt.','Foot → feet.']],'Nicht childrens, foots oder peoples für mehrere Personen.'),
('words','Typische Verwechslungen','Englische Ausdrücke statt wörtlicher Übersetzung.', ['Watch TV: bewusst ansehen; see: sehen. Teach: beibringen; learn: lernen.','Look for: suchen; look after: sich kümmern um.','Happy: froh/glücklich; lucky: Glück haben. Become: werden.','Bored/excited beschreiben Gefühle; boring/exciting das, was diese Gefühle auslöst.','Want + Person + to + Verb: I want you to help. It is fun = Es macht Spaß.','Nationalitäten und Sprachen groß: British, Australian, English.','Know = wissen; now = jetzt. Ordnungszahlen: first, second, third, fourth, fifth.'],[['The game is exciting. I am excited.','Ursache und Gefühl unterscheiden.'],['She wants me to help.','Kein that-Satz nach want in dieser Bedeutung.']],'Die deutsche Formulierung lässt sich oft nicht direkt ins Englische übertragen.')]
curriculum=json.loads((R/'content/curriculum.json').read_text())
questions=[];topic=None;counter=0
for line in (R/'content/practice.txt').read_text().splitlines():
 if not line:continue
 if line.startswith('# '):topic=line[2:];counter=0;continue
 counter+=1;p,a,e=line.split('|');questions.append(dict(id=f'n-{topic}-{counter:02}',topic=topic,prompt=p,answers=a.split(';'),explanation=e,year=0,independent=True,level='basic' if counter<=4 else 'apply' if counter<=8 else 'transfer',source='Neue Übung · Klasse 7',instruction='Trage nur die gesuchte Antwort ein.',caseSensitive=topic=='words' and counter==7))
assert len(questions)==168
for q in questions:
 original_id=q['id']
 q['curriculumGrades']=curriculum['question_grades'][original_id]
 if original_id in curriculum['revised_ids']:q['id']=original_id+'-lp56'

# Keep existing question IDs and answer keys when changing only the input control.
for q in questions:
 q['type']='input'
 match=re.search(r'\(([^()]+ / [^()]+)\)[.!?]?$',q['prompt'])
 if match:
  options=match.group(1).split(' / ')
  normal=lambda v: v.strip().replace('’', "'") if q.get('caseSensitive') else v.strip().replace('’', "'").lower()
  valid=[o for o in options if normal(o) in [normal(a) for a in q['answers']]]
  if len(valid)==1:
   q['type']='choice';q['options']=options;q['prompt']=q['prompt'][:match.start()].strip()
   q['instruction']='Wähle die passende Antwort aus.'
for q in json.loads((R/'content/varied-exercises.json').read_text()):
 q.update(year=0,independent=True,level='transfer',source='Neue Übung · Klasse 7',caseSensitive=False)
 questions.append(q)
assert len(questions)==196

exams=json.loads((R/'content/exams.json').read_text())
grammar=[]
for id,title,sub,forms,examples,trap in chapters:
 years=[int(y) for y,e in exams.items() if any(q['topic']==id for q in e['grammar'])]
 if not years:years=['Grundlage']
 grammar.append(dict(curriculumGrades=curriculum['chapter_grades'][id],id=id,title=title,sub=sub,rule=forms[0],forms=forms,examples=examples,trap=trap,years=years))
plan=[['Lerncheck','Finde die Themen, bei denen du noch unsicher bist.','diagnostic',15],['Gegenwart & Vergangenheit','Wiederhole Grundformen und die Vergangenheit.','topic:past',20],['Present perfect verstehen','Vergangene Handlungen und ihr Ergebnis jetzt unterscheiden.','topic:perfect',20],['Fragen sicher bilden','Fragen und kurze Frageanhänge üben.','topic:questions',15],['Können, müssen, dürfen','Modalverben und ihre Ersatzformen festigen.','topic:modals',20],['Vergleichen & Mengen','Übe Steigerung und passende Vergleichswörter.','topic:comparison',15],['Kleine Wörter, klare Sätze','Pronomen und Besitzangaben wiederholen.','topic:pronouns',15],['Gemischte Übungsrunde','Wende dein Wissen in neuen Sätzen an.','mixed',20],['Fehlerwerkstatt','Schau dir offene Fehler an und löse sie erneut.','mistakes',15],['Originaltest 2021','Bearbeite erstmals einen vollständigen Test.','exam:2021',50],['Weitere Generalprobe','Probiere einen anderen Jahrgang unter Zeitbedingungen.','exams',50]]
data=dict(curriculum=dict(checked=curriculum['checked'],scope=curriculum['scope'],sources=curriculum['sources']),grammar=grammar,questions=questions,plan=[['',*p] for p in plan],years=[dict(year=int(y),listening=e['title'],writing=e['writingTitle'],words=140,page=e['writingPage'],**e['files']) for y,e in sorted(exams.items(),reverse=True)])
(R/'dist/data.js').write_text('window.LAB_DATA = '+json.dumps(data,ensure_ascii=False,separators=(',',':'))+';\n')
print('Built 14 chapters, 196 independent exercises and an undated plan.')
